version: '3.8'

networks:
  aerospike-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server:latest
    ports:
      - "3000:3000"
    networks:
      - aerospike-net

#  aerospike-tools:
#    container_name: aerospike-tools
#    image: aerospike/aerospike-tools:latest
#    depends_on:
#      - aerospike
#    command: [asadm, -haerospike]
#    stdin_open: true
#    networks:
#      - aerospike-net

  aerospike-exporter:
    image: aerospike/aerospike-prometheus-exporter:latest
    container_name: aerospike-exporter
    restart: unless-stopped
    environment:
      - AS_HOST=host.docker.internal
      - AS_PORT=3000
      - "METRIC_LABELS=type='development',source='aerospike',latitude='0',longitude='0'"
    ports:
      - "9145:9145"
    networks:
      - aerospike-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - aerospike-net
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - aerospike-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "4000:3000"
    networks:
      - aerospike-net
