global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "aerospike"
    static_configs:
      - targets: ["aerospike-exporter:9145"]

  - job_name: "promtheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
